[build-system]
requires = ["setuptools>=77", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "GenTS"
dynamic = ["version"]
authors = [
  { name="Cameron Cummins", email="cameron.cummins@utexas.edu" },
]
description = "A useful tool for post-processing Earth System Model output 'history files' into the time series format."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = [
  "numpy>=2.0",
  "netCDF4>=1.7.0",
  "cftime>=1.6.4",
  "pyyaml>=3.01"
]
classifiers = [
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Operating System :: OS Independent",
]

[tool.setuptools_scm]
fallback_version = "0.0.0"

[project.urls]
Homepage = "https://github.com/AgentOxygen/GenTS"
Issues = "https://github.com/AgentOxygen/GenTS"

[tool.setuptools]
packages = ["gents", "gents.configs"]

[tool.setuptools.package-data]
"gents.configs" = ["*.yaml"]

[project.scripts]
run_gents = "gents.cli:main"

[project.optional-dependencies]
test = ["pytest"]
docs = ["sphinx", "sphinx-autobuild"]
bench = ["asv"]
dev = ["GenTS[test,docs,bench]"]
