name: Run Unit Tests

on:
  push:
    branches: [main]
    paths: ['**.py', 'pyproject.toml', 'Dockerfile']
  pull_request:
    paths: ['**.py', 'pyproject.toml', 'Dockerfile']


jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build image
        run: docker build --target test -t gents-tests .

      - name: Run unit tests
        run: docker run --rm gents-tests